"set t_Co=256
syntax on
"colorscheme evening
colorscheme Mustang

set autoindent
set ruler
set hlsearch
set cursorline
set cursorcolumn
set spelllang=de,en
set spell
set showcmd
set backspace=2

" Haskell
au Bufenter *.hs compiler ghc
let g:haddock_browser = "open"
let g:haddock_browser_callformat = "%s %s"
let g:haddock_indexfiledir = "$HOME/.vim/"

filetype plugin on
filetype plugin indent on


autocmd FileType htmldjango set ft=htmldjango.html " For SnipMate


if version >= 703
	set colorcolumn=81
endif


if(match(hostname(), 'macmini') >= 0)
	set gfn=Monaco:h13
elseif(match(hostname(), 'janneke') >= 0)
	set gfn=Monaco:h15
endif

if has("gui_running")
	set number
	set guioptions-=T
	set columns=86
	set lines=45
	set clipboard=unnamed
endif

let mapleader = ","
map <Leader>n :NERDTreeToggle<CR>


